project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("viewer.urls"))
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

viewer/urls.py
from . import views

from django.urls import path

app_name = "viewer"

urlpatterns = [
    path("", views.video_clips, name="video_clips"),
    path("video/<int:video_id>/", views.video_clip_detail, name="video_target")
]

viewer/models.py
from django.db import models
from django.core.validators import FileExtensionValidator


def create_course(self, filename):
    return f"{self.course.category.name}/{self.course.name}/{filename}"


class Category(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Course(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE, default="")
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class ClipsModel(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE, related_name="course")
    video = models.FileField(null=False,
                             validators=[
                                 FileExtensionValidator(
                                     allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])
                                 ],
                             upload_to=create_course
                             )
    viewed = models.BooleanField(default=False)

    def __str__(self):
        return str(self.id)

    class Meta:
        ordering = ('-video',)

viewer/views.py
# Django Apps
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator
# Apps
from .models import ClipsModel, Course
from viewer.pagers import page_navigation


def filter_videos(tag_list_request: list) -> ClipsModel.objects.all():
    # Videos Query-sets
    queryset = ClipsModel.objects.all()

    if tag_list_request:
        queryset = queryset.filter(course__name__in=tag_list_request)

    return queryset


# Get the list of video project
def video_clips(request):
    tags = Course.objects.all()
    choices_list = request.GET.getlist("choices")
    videos = filter_videos(choices_list)
    paginator = Paginator(videos, 48)
    page_number = request.GET.get('page')
    get_page = paginator.get_page(page_number)
    pager = page_navigation(get_page, page_number)

    context = {
        "tags": tags,
        "choices": choices_list,
        'next_url': pager['next_url'],
        'prev_url': pager['prev_url'],
        'videos': get_page,
        'is_pager': pager['is_pager']
    }
    return render(request, "clip_temp/video_clips.html", context)


def video_clip_detail(request, video_id=None):
    video = get_object_or_404(ClipsModel, id=video_id)
    video.viewed = True
    video.save()
    return render(request, "clip_temp/video_clip_detail.html", {'video': video})

templates/base.html
<!DOCTYPE html>
<html lang="en">
    {% load static %}
    <head>
        <meta charset="UTF-8">
        <title>{% block title %} Base {% endblock %}</title>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- Bootstrap -->
        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    </head>
    <body>
        {% block body %}
        {% endblock %}
        <script src="{% static 'js/custom.js' %}"></script>
    </body>
</html>

templates/clip_temp/video_clip_detail.html
{% extends 'base.html' %}
{% block title %} {{ video.video }} {% endblock %}

{% block body %}
    <div class="video-clip-id">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <video autoplay controls src="{{ video.video.url }}"></video>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/clip_temp/video_clips.html
{% extends 'base.html' %}
{% block title %} List of videos {% endblock %}

{% block body %}
    {% load filter %}
    <div class="video-clip">
        <div class="container">
            <div class="filteration">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="filter-nav mt-2 mb-2">
                            <form method="get">
                                {{ request.GET.getlist.choices }}
                                {% for tag in tags %}
                                    <div class="mt-2 d-inline-block">
                                        <input
                                            type="checkbox"
                                            class="tags choices"
                                            id="{{ tag.id }}"
                                            {% if tag.name in choices %}
                                            checked
                                            {% endif %}
                                            name="choices"
                                            value="{{ tag.name }}"
                                            {% if tag.name in choices %}
                                            data-checked="checked"
                                            {% else %}
                                            data-checked=""
                                            {% endif %}
                                        >

                                        <label class="tag-label" for="{{ tag.id }}">{{ tag.name }}</label>
                                    </div>
                                {% endfor %}
                                <input type="submit" hidden id="filter-data">
                            </form>
                        </div>
                    </div>
                </div>
            </div>
            <div class="video-clip-list">
                <div class="row">
                    {% for video in videos.object_list %}
                        <a href="{% url 'viewer:video_target' video.id %}">
                            <div class="col-md-4 add-video">
                                <video autoplay muted loop src="{{ video.video.url }}"></video>
                                {% if video.viewed %}
                                    <span id="checked"></span>
                                {% endif %}
                                <br>
                            </div>
                            <span>{% video_name video.video.name %}</span>
                        </a>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
    {% if videos %}
        {% if is_pager is True %}
            <div class="row">
        <div class="col-lg-12 text-center">
            <ul class="pagination">
                <li class="page-item not-active{% if not prev_url %} disabled {% endif %}">
                    <a class="page-link" href="{{ prev_url }}">
                        <i class="fas fa-chevron-left"></i>
                    </a>
                </li>

                {% for n in videos.paginator.page_range %}
                    {% if videos.number == n %}
                        <li class="page-item active">
                            <a class="page-link" href="?page={{ n }}">
                                {{ n }}
                                <span class="sr-only">(current)</span>
                            </a>
                        </li>
                    {% elif n > videos.number|add:-4 and n < videos.number|add:4 %}
                        <li class="page-item not-active">
                            <a class="page-link" href="?page={{ n }}">
                                {{ n }}
                            </a>
                        </li>
                    {% endif %}
                {% endfor %}

                <li class="page-item not-active{% if not next_url %} disabled {% endif %}">
                    <a class="page-link" href="{{ next_url }}">
                        <i class="fas fa-chevron-right"></i>
                    </a>
                </li>
            </ul>
        </div>
    </div>
        {% endif %}
    {% endif %}
    <script>
        let tag_label = document.querySelectorAll(".tag-label");
        let submit_btn = document.getElementById("filter-data");
        let tag_form = document.querySelector("form");

        function click_label(tag_list) {
            for (let i = 0; i < tag_list.length; i++) {
                tag_list[i].addEventListener('click', function (e) {
                    setTimeout(() => {
                        tag_form.submit();
                    }, 50);
                });
            }
        }
        click_label(tag_label);
    </script>
{% endblock %}